# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-12-05 17:28:05
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Contours_1_ft_Intervals_ = "Contours_(1_ft_Intervals)"
    Parcels = "Parcels"

    for Value in range(851, 853, 1):

        # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
        Updated_Layer_Or_Table_View, Count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=Contours_1_ft_Intervals_, selection_type=Value)

        # Process: Dissolve (Dissolve) (management)
        Contours_1_ft_Inter_Dissolve1 = "C:\\Users\\carso\\OneDrive\\Documents\\ArcGIS\\Projects\\inclass7\\inclass7.gdb\\Contours_1_ft_Inter_Dissolve1"
        arcpy.management.Dissolve(in_features=Updated_Layer_Or_Table_View, out_feature_class=Contours_1_ft_Inter_Dissolve1, dissolve_field=["ELEVATION"], statistics_fields=[["ELEVATION", "MEAN"]])

        # Process: Select Layer By Location (Select Layer By Location) (management)
        Contours_1_ft_Inter_Dissolve1_2_, Output_Layer_Names, Count_2_ = arcpy.management.SelectLayerByLocation(in_layer=[Contours_1_ft_Inter_Dissolve1], select_features=Parcels, search_distance="2 Feet")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\carso\\OneDrive\\Documents\\ArcGIS\\Projects\\inclass7\\inclass7.gdb", workspace="C:\\Users\\carso\\OneDrive\\Documents\\ArcGIS\\Projects\\inclass7\\inclass7.gdb"):
        Model()
