# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-12-05 18:50:44
"""
import arcpy
import pandas as pd


def Model():  # Model
    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(
        r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Conversion Tools.tbx"
    )
    Contours_1_ft_Intervals_ = "Contours_(1_ft_Intervals)"
    Parcels = "Parcels"

    total = 0
    for Value in range(851, 860, 1):
        # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
        Contours_1_ft_Intervals_3_, Count = arcpy.management.SelectLayerByAttribute(
            in_layer_or_view=Contours_1_ft_Intervals_,
            selection_type="NEW_SELECTION",
            where_clause=Value,
            invert_where_clause="NON_INVERT",
        )

        # Process: Dissolve (Dissolve) (management)
        Contours_1_ft_Inter_Dissolve1 = "C:\\Users\\carso\\OneDrive\\Documents\\ArcGIS\\Projects\\inclass7\\inclass7.gdb\\Contours_1_ft_Inter_Dissolve1"
        arcpy.management.Dissolve(
            in_features=Contours_1_ft_Intervals_3_,
            out_feature_class=Contours_1_ft_Inter_Dissolve1,
            dissolve_field=["ELEVATION"],
            statistics_fields=[["ELEVATION", "MEAN"]],
        )

        # Process: Select Layer By Location (Select Layer By Location) (management)
        (
            Parcels_2_,
            Output_Layer_Names,
            Count_2_,
        ) = arcpy.management.SelectLayerByLocation(
            in_layer=[Parcels],
            select_features=Contours_1_ft_Inter_Dissolve1,
            search_distance="2 Feet",
        )

        # Process: Table To Excel (Table To Excel) (conversion)
        challenge_12_data_xls = "C:\\Users\\carso\\OneDrive - UW-Madison\\23_24_Fall\\econ695\\data\\challenge_12_data.xls"
        arcpy.conversion.TableToExcel(
            Input_Table=[Parcels_2_], Output_Excel_File=challenge_12_data_xls
        )

        # calculate sum
        df = pd.read_excel("../data/challenge_12_data.xls")
        total += df["priceperac"].sum()


if __name__ == "__main__":
    # Global Environment settings
    with arcpy.EnvManager(
        scratchWorkspace="C:\\Users\\carso\\OneDrive\\Documents\\ArcGIS\\Projects\\inclass7\\inclass7.gdb",
        workspace="C:\\Users\\carso\\OneDrive\\Documents\\ArcGIS\\Projects\\inclass7\\inclass7.gdb",
    ):
        Model()
